[creator]
type = "user"
id = 9962048442

[codegen]
typescript = false
style = "nested"
strip_extensions = true

[inputs.Asphalt]
path = "assets/asphalt/**/*"
output_path = "src/UserInterface"
bleed = true